export const GET_ALL_PRODUCT_USER_REQUEST = "GET_ALL_PRODUCT_USER_REQUEST"
export const GET_ALL_PRODUCT_USER_SUCCESS = "GET_ALL_PRODUCT_USER_SUCCESS"
export const GET_ALL_PRODUCT_USER_FAIL = "GET_ALL_PRODUCT_USER_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"